### ISSUE TITLE
Add native autocomplete="off" to input

### ISSUE THREAD

**Issue by galaczi** [Sourabhpatel1/svelte-combobox#1]
After selecting an option, Chrome takes note of that and natively offers to autocomplete the form next time you click in it. That traps keyboard actions and covers the other options. In my opinion autocomplete="off" would be a good default. If not, a prop to set it would be sufficient as well.

**Comment by Sourabhpatel1** [comment]
I've added `autocomplete="off"` to the input element please check if the issue is gone is still there. appreciate the info. I am using Brave browser and I could not replicate the problem mentioned.

**Comment by galaczi** [comment]
It's probably different browser settings. I can confirm it solved the issue on my end.
